# Generated by Django 4.0.2 on 2022-06-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dept_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='dept_name',
            new_name='name',
        ),
    ]
